//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZXRM.PSS.WebClient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetrocoalEntities : DbContext
    {
        public PetrocoalEntities()
            : base("name=PetrocoalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Seiving> Seivings { get; set; }
        public virtual DbSet<SeivingSizeQty> SeivingSizeQties { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
    }
}
