//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZXRM.PSS.WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seiving
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seiving()
        {
            this.SeivingSizeQties = new HashSet<SeivingSizeQty>();
        }
    
        public int ID { get; set; }
        public string SeivingNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StoreId { get; set; }
        public Nullable<int> VesselId { get; set; }
        public string FromSize { get; set; }
        public Nullable<decimal> FromQuantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Origin { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeivingSizeQty> SeivingSizeQties { get; set; }
    }
}
