//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZXRM.PSS.WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeivingSizeQty
    {
        public long ID { get; set; }
        public Nullable<int> SeivingID { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<decimal> SizeQuantity { get; set; }
    
        public virtual Seiving Seiving { get; set; }
    }
}
